// Questions
var q = [
	'What&#39;s an impressive thing you have done?',
	'What domain expertise do you have?',
	'What systems have you hacked?',
	'Tell us about a tough problem you solved?',
	'Tell us something surprising you have done?',
	'What&#39;s the funniest thing that has happened to you?',
	'What&#39;s the worst thing that has happened?',
    'What&#39;s a complex topic that you understand, how would you explain it to someone with no background or experience in that area?',
    'What do you do when you are not working?',
    'What is the biggest professional mistake you have done?',
    'What business would you like to start if you had the chance?',
    'On a scale of 1-10 how weird are you and why?',
    'Tell me a little bit about yourself?',
    'What are your three greatest strengths and weaknesses?',
    'What is your dream job?',
    'Where do you see yourself professionally in 10 years?',
    'If you had to describe your personality in three words, what would you choose?',
    'What do you do to relax?',
    'Which talent do you have outside of your career?',
    'What is a recent skill you have learned outside of your career?',
    'How do you handle multiple assignments at once?',
    'If you could choose one superpower, what would it be?',
    'Why are you a good fit for this position?',
    'Why do you want to work for this company?',
    'What would your previous supervisor say about your work?',
    'How would your former coworkers describe you?',
    'What was your favorite job you held so far?',
    'What is the best professional advice you have ever received?',
    'Which professional accomplishment are you most proud of?',
    'What are the most relevant skills that will help you thrive in this role?',
    'If you were to launch your own startup, what would it be?',
    'Who are our biggest competitors and how would you sum up our business model?',
    'What do you think we should focus on in the upcoming years?',
    'What are you bringing to the table that other candidates can not provide?',
    'Do you perform best alone or as part of a team?',
    'Why work in a startup?', // to delete if not startup
    'Do you prefer working remotely or in person?',
    'What can you actually do for us?',
    'Describe yourself in one sentence?',
    'Tell me about your current job, what do you like and why do you want to leave?',
    'What will you do if you are unsuccessful in securing this opportunity?',
    'Why are you leaving your current position?',
    'How do you manage stress and conflict at work?',
    'Why did you choose to study your current degree?', // to delete if no student
    'How do you think this company might grow over the next three years?',
    'In what areas do you think you still need to develop?',
    'What traits do you value most in team members?',
    'What kind of work environment do you prefer to work in?',
    'How do you deal with criticism?',
    'Is there something you would like to ask us?',
    'What skills are you lacking?',
    'What is annoying you?',
    'What is your previous experience in the field?',
    'What is an interesting startup you are currently looking into?',
    'How did you find out about this opportunity?',
    'What is a recent news that you found interesting/intruiging?',
    'Do you like NFTs?',
    'Describe a complex technical problem you had to solve.',
    'What are the reasons behind the failure of your startup? What could you have done to avoid it?',
    'Why did you decide to found a startup and what did you try to achieve?',
    'What did you learn from the failure of your startup and how can you use this experience in your future career?',
    'Please explaint your experience at BOAS, what was your role? Why do you want to leave for this internship?',
    'Why do you think that the European health system is broken? What would need to be improved?',
    'There are plenty of students applying from your university with equal or better work experience, why should we hire you?',
    'What are your most important values?',
	'What&#39;s the biggest mistake you have made?'

];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to founders and other accomplished professionals, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'Try to match their tempo (as you should when talking to anyone).'
];